<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GSIP.Infrastructure</AssemblyName>
    <RootNamespace>GSIP.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <ProjectReference Include="..\GSIP.Application\GSIP.Application.csproj" />
    <ProjectReference Include="..\GSIP.Domain\GSIP.Domain.csproj" />
  </ItemGroup>
</Project>
