<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>GSIP.P02SqlAuthChecks</AssemblyName>
    <RootNamespace>GSIP.P02SqlAuthChecks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\GSIP.Application\GSIP.Application.csproj" />
    <ProjectReference Include="..\..\src\GSIP.Infrastructure\GSIP.Infrastructure.csproj" />
  </ItemGroup>
</Project>
